version: 2
jobs:
  build:
    working_directory: ~/JavaScriptApiAutomation
    docker:
      - image: circleci/node:8.0
      - image: mongo:3.4.4
    steps:
      - run:
          name: "Checking NodeJs + NPM Version"
          command: |
            node --version
            npm --version
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Mocha
          command: 'sudo npm i -g mocha'
      - run:
          name: Run API Tests
          command: 'npm test'
